GET http://localhost:3001/api/notes

###
GET http://localhost:3001/api/notes/63d518a3eb9ef2c999fd7adb

###
DELETE http://localhost:3001/api/notes/4

###
POST http://localhost:3001/api/notes HTTP/1.1
Content-Type: application/json

{
    "content": "CSS is the design means for web docs.",
    "important": true
}

###
PUT http://localhost:3001/api/notes/63df6cf6eb6a013d64eca998 HTTP/1.1
Content-Type: application/json

{
    "content": "lol",
    "important": true
}